### ISSUE TITLE
关于hxcpp

### ISSUE THREAD

**Issue by lighter-cd** [R32/r32.github.io#1]
刚学hxcpp.想问下博主 只用hxcpp不用NME的情况下，应该怎么设置，才能编译到 android和ios平台

**Comment by R32** [comment]
其实编译成 cpp 代码时加上 `-D android` 就行了, 比如:

```bash
haxe -cp src -main HelloWorld -cpp bin -D android
```
hxcpp 会自动选择 ndk 编译器编译(参考下 hxcpp/toolchain 下的配置文件)， 我觉得还是参考下 NME 或 luxe 这些库是如何做的会更好, 我也有段时间没关注 hxcpp 一些细节可能也不清楚
